/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uth.hn.PA1.parcial1.aplicacion;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import uth.hn.PA1.parcial1.aplicacion.objeto.Contador;

/**
 *
 * @author Gustavo
 */
public class frmCandidatos_GustavoLagos extends javax.swing.JFrame {

    /**
     * Creates new form frmCandidatos_GustavoLagos
     */
    public frmCandidatos_GustavoLagos() {
        this.funcionalice = new Contador();
        this.funcionasok = new Contador();
        this.funciondilbert = new Contador();
        initComponents();
        this.repaint();
        ImageIcon imagenDIl= new ImageIcon(getClass().getResource("/imagen/dilbert.jpg"));
        Icon DIl = new ImageIcon(imagenDIl.getImage().getScaledInstance(lblimagendil.getWidth(), lblimagendil.getHeight(), Image.SCALE_DEFAULT));
        lblimagendil.setIcon(DIl);
        this.repaint();
        ImageIcon imagenAlice= new ImageIcon(getClass().getResource("/imagen/alice.jpg"));
        Icon Alice = new ImageIcon(imagenAlice.getImage().getScaledInstance(lblimagenalice.getWidth(), lblimagenalice.getHeight(), Image.SCALE_DEFAULT));
        lblimagenalice.setIcon(Alice);
        this.repaint();
        ImageIcon imagenAsok= new ImageIcon(getClass().getResource("/imagen/asok.jpg"));
        Icon ask = new ImageIcon(imagenAsok.getImage().getScaledInstance(lblimagenasok.getWidth(), lblimagenasok.getHeight(), Image.SCALE_DEFAULT));
        lblimagenasok.setIcon(ask);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEleccionesHonduras = new javax.swing.JLabel();
        lblcandidatos = new javax.swing.JLabel();
        lblimagenasok = new javax.swing.JLabel();
        lblimagenalice = new javax.swing.JLabel();
        lblimagendil = new javax.swing.JLabel();
        lbldilbert = new javax.swing.JLabel();
        lblasok = new javax.swing.JLabel();
        lblalice = new javax.swing.JLabel();
        btnAlice = new javax.swing.JButton();
        btnDilbert = new javax.swing.JButton();
        btnAsok = new javax.swing.JButton();
        txtdilbert = new javax.swing.JTextField();
        txtasok = new javax.swing.JTextField();
        txtalice = new javax.swing.JTextField();
        jpbD = new javax.swing.JProgressBar();
        jpbA = new javax.swing.JProgressBar();
        jpbAsok = new javax.swing.JProgressBar();
        btnReinicio = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEleccionesHonduras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEleccionesHonduras.setText("Elecciones Honduras");

        lblcandidatos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblcandidatos.setText("Candidatos");

        lblimagenasok.setBorder(new javax.swing.border.MatteBorder(null));

        lblimagenalice.setBorder(new javax.swing.border.MatteBorder(null));

        lblimagendil.setBorder(new javax.swing.border.MatteBorder(null));

        lbldilbert.setText("Dilbert");

        lblasok.setText("Asok");

        lblalice.setText("Alice");

        btnAlice.setText("Votar+1");
        btnAlice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAliceMouseClicked(evt);
            }
        });
        btnAlice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAliceActionPerformed(evt);
            }
        });

        btnDilbert.setText("Votar+1");
        btnDilbert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDilbertMouseClicked(evt);
            }
        });
        btnDilbert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDilbertActionPerformed(evt);
            }
        });

        btnAsok.setText("Votar+1");
        btnAsok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsokMouseClicked(evt);
            }
        });

        jpbD.setMaximum(20);

        jpbA.setMaximum(20);

        jpbAsok.setMaximum(20);

        btnReinicio.setText("Iniciar de nuevo");

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblimagendil, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpbD, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnDilbert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtdilbert))
                        .addGap(36, 36, 36)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAlice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtalice)
                            .addComponent(jpbA, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblimagenalice, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblimagenasok, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAsok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtasok)
                                .addComponent(jpbAsok, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(lblEleccionesHonduras))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(lbldilbert)
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblalice))
                                    .addComponent(lblcandidatos))))
                        .addGap(10, 10, 10)
                        .addComponent(lblasok))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnReinicio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblEleccionesHonduras)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblasok)
                        .addGap(18, 18, 18)
                        .addComponent(lblimagenasok, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcandidatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblalice)
                            .addComponent(lbldilbert))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblimagenalice, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblimagendil, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDilbert)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAlice)
                        .addComponent(btnAsok)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdilbert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jpbD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpbAsok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpbA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReinicio)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 Contador funciondilbert = new Contador();
 Contador funcionalice= new  Contador();;
 Contador funcionasok =new Contador();
    
    private void btnDilbertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDilbertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDilbertActionPerformed

    private void btnAliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAliceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAliceActionPerformed

    private void btnDilbertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDilbertMouseClicked
     funciondilbert.contadorD();
     txtdilbert.setText(String.valueOf(funciondilbert.getVotoD()));
     jpbD.setValue(funciondilbert.getVotoD());
     jpbD.setVisible(true);
     String votoDi= txtdilbert.getText();
     if(votoDi.equals("20")){
         JOptionPane.showMessageDialog(null,"El ganador es Dilbert");
    }//GEN-LAST:event_btnDilbertMouseClicked
}
    private void btnAliceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAliceMouseClicked
           funcionalice.contadorAL();
       txtalice.setText(String.valueOf(funcionalice.getVotoA()));
       jpbA.setValue(funcionalice.getVotoA());
       jpbA.setVisible(true);
       String votoAlice= txtalice.getText();
       if(votoAlice.equals("20")){
           JOptionPane.showMessageDialog(null, "El ganador es Alice");
    }//GEN-LAST:event_btnAliceMouseClicked
}
    private void btnAsokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsokMouseClicked
 funcionasok.contadorAS();
       txtasok.setText(String.valueOf(funcionasok.getVotoa()));
       jpbAsok.setValue(funcionasok.getVotoa());
       jpbAsok.setVisible(true);
       String votoAsok= txtasok.getText();
       if(votoAsok.equals("20")){
           JOptionPane.showMessageDialog(null, "El ganador es Asok");        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsokMouseClicked
}
    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
       System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked
 
  

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCandidatos_GustavoLagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCandidatos_GustavoLagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCandidatos_GustavoLagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCandidatos_GustavoLagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(  frmCandidatos_GustavoLagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(  frmCandidatos_GustavoLagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(  frmCandidatos_GustavoLagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(  frmCandidatos_GustavoLagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCandidatos_GustavoLagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlice;
    private javax.swing.JButton btnAsok;
    private javax.swing.JButton btnDilbert;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JProgressBar jpbA;
    private javax.swing.JProgressBar jpbAsok;
    private javax.swing.JProgressBar jpbD;
    private javax.swing.JLabel lblEleccionesHonduras;
    private javax.swing.JLabel lblalice;
    private javax.swing.JLabel lblasok;
    private javax.swing.JLabel lblcandidatos;
    private javax.swing.JLabel lbldilbert;
    private javax.swing.JLabel lblimagenalice;
    private javax.swing.JLabel lblimagenasok;
    private javax.swing.JLabel lblimagendil;
    private javax.swing.JTextField txtalice;
    private javax.swing.JTextField txtasok;
    private javax.swing.JTextField txtdilbert;
    // End of variables declaration//GEN-END:variables

}